import { useState, type SyntheticEvent } from "react";

type Props = { photos: string[] };

/**
 * Turn an original photo URL into the URL of its thumbnail. Thumbs live next
 * to the original in a sibling `thumbs/` folder with the same filename:
 *   photos/<slug>/foo.jpg  →  photos/<slug>/thumbs/foo.jpg
 * Generated by `npm run thumbnails` (scripts/generate-thumbnails.mjs).
 *
 * Falls back to the original at render-time if the thumb is missing — see
 * the onError handler below — so this is safe even before the script has
 * been run for a new album.
 */
function thumbUrl(src: string): string {
  const i = src.lastIndexOf("/");
  if (i < 0) return src;
  return `${src.slice(0, i)}/thumbs${src.slice(i)}`;
}

export default function PhotoGallery({ photos }: Props) {
  const [open, setOpen] = useState<string | null>(null);

  // If a thumb 404s (e.g. you added a new photo and forgot to regenerate
  // thumbs), point the <img> at the original instead. Marking the element
  // with a data attribute prevents an infinite loop if the original is also
  // missing.
  const handleThumbError = (
    e: SyntheticEvent<HTMLImageElement>,
    original: string,
  ) => {
    const img = e.currentTarget;
    if (img.dataset.fallback === "true") return;
    img.dataset.fallback = "true";
    img.src = original;
  };

  return (
    <>
      <div className="photo-grid">
        {photos.map((src) => (
          <button
            key={src}
            className="photo-thumb"
            onClick={() => setOpen(src)}
            aria-label="Open photo"
          >
            <img
              src={thumbUrl(src)}
              alt=""
              loading="lazy"
              decoding="async"
              onError={(e) => handleThumbError(e, src)}
            />
          </button>
        ))}
      </div>
      {open && (
        <div
          className="photo-lightbox"
          role="dialog"
          aria-modal
          onClick={() => setOpen(null)}
        >
          {/* Lightbox keeps using the full-resolution original. */}
          <img src={open} alt="" />
          <button
            className="photo-close"
            onClick={() => setOpen(null)}
            aria-label="Close"
          >
            ×
          </button>
        </div>
      )}
    </>
  );
}
